---
- name: restart network
  systemd:
    name: "{{ network_service }}"
    state: restarted
  when: network_allow_service_restart

- name: toggle interface
  include_tasks: handlers/toggle_interface.yml
  when: network_allow_service_restart and network_service == "NetworkManager"
