---
- name: Update facts
  setup:
- name: toggle any interface still having same ip as its bond
  shell: "nmcli device disconnect {{ item.1 }} && sleep 15 && nmcli device connect {{ item.1 }}"
  when:
    - hostvars[inventory_hostname]['ansible_' + (item.0.device | replace('-','_'))].ipv4.address is defined
    - hostvars[inventory_hostname]['ansible_' + (item.1 | replace('-','_'))].ipv4.address is defined
    - hostvars[inventory_hostname]['ansible_' + (item.0.device | replace('-','_'))].ipv4.address == hostvars[inventory_hostname]['ansible_' + (item.1 | replace('-','_'))].ipv4.address
  loop: "{{ query('subelements', network_bond_interfaces, 'bond_slaves') }}"
...
